### PR TITLE
Update to support new Module API

### PR DESCRIPTION
**Pull request by amccloud**
https://github.com/facebook/react-native/commit/bc28a35bda0e358a8296a7b53eb7315b736c6e4b

### CODE REVIEW

**Comment by elliottsj** [comment]
I wasn't able to get your changes working with react native 0.9.0. The server hangs at

```
Server listening at http://localhost:8080
```

I think it may be due to the `dependency.isPolyfill` -> `dependency.isPolyfill()` change. Closing for now; make a PR on https://github.com/mjohnston/react-native-webpack-server though!

**Comment by amccloud** [comment]
@elliottsj The API in 0.9.0 appears to be temporary. I believe in 0.10+ the module API has been formalized which is what my code was expecting.

**Comment by amccloud** [comment]
@elliottsj The API in 0.9.0 appears to be temporary. I believe in 0.10+ the module API has been formalized which is what my code was expecting.

**Comment by elliottsj** [comment]
@amccloud Ah, makes sense. I'm alright with breaking compatibility with pre-0.10.0 versions, though I'm not sure if it's ok with @mjohnston or other users.

**Pull request closed without merging**
